### ISSUE TITLE
W3C Vision: wide and horizontal reviews tracking

### ISSUE THREAD

**Issue by tantek** [w3c/AB-public#195]
This is primarily a project tracking issue for the Vision Task Force (VisionTF) editor and chair. There are a number of required and a few optional but helpful steps to take before taking the W3C Vision to the Advisory Committee for a vote for a Statement. Notably we need to ensure that proper wide and horizontal reviews have been explicitly requested, and any requests back for more time are properly incorporated.

Here are check-lists of explicit requests for horizontal and wide reviews for customary durations per the W3C Process, with issue links to be added to track each individual request. Checklist items are initially intended for keeping track of sending requests for reviews, without implying anything about the outcomes thereof. We should also track when we have at a minimum received review feedback from each group that can provide summary feedback from that group.

Before we send these requests for review, we need to publish an updated AB-approved (tracked in the AB’s Member-only repo) public Note based on the current Editor’s draft, for the reviewers to consider:

  * [x] Publish AB-approved updated public Note ([AB-memberonly #242](https://github.com/w3c/AB-memberonly/issues/242))

## Horizontal Reviews Requests

  * [x] Accessibility (a11y) - https://github.com/w3c/a11y-request/issues/93
  * [x] Internationalization (i18n) - https://github.com/w3c/i18n-request/issues/243
  * [x] Privacy - https://github.com/w3cping/privacy-request/issues/145
  * [x] Security - https://github.com/w3c/security-request/issues/77
  * [x] Technical Architecture Group (TAG) - https://github.com/w3ctag/design-reviews/issues/1008

## Wide Reviews Requests

  * [x] public-review-announce list - https://lists.w3.org/Archives/Public/public-review-announce/2024Oct/0005.html
  * [x] Advisory Committee (AC) - https://lists.w3.org/Archives/Member/w3c-ac-forum/2024OctDec/0074.html (W3C Member-only link)
  * [x] Board of Directors (Board) - largely same content as ^, addressed to Members of the W3C Board of Directors
  * [x] Positive Work Environment Task Force (PWETF) - https://lists.w3.org/Archives/Public/public-pwe/2024Oct/0002.html

### Wider Outreach

In addition, for such a foundational document, I believe its wide review can benefit from the following optional steps to reach an audience beyond W3C who may have feedback for our consideration:

  * [ ] Blog post on W3.org requesting wide review
  * [ ] One or more personal blog posts by editor and/or chair
  * [ ] Social media copies of or links to said blog posts

Label: Project Vision

(Originally published at: https://tantek.com/2024/281/b1/)

**Comment by plehegar** [comment]
fyi, see also [How to do Wide Review](https://www.w3.org/Guide/documentreview/)
